#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkCycleListener.DataModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MfrMachineDataLaptop")]
	public partial class AssetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAsset(Asset instance);
    partial void UpdateAsset(Asset instance);
    partial void DeleteAsset(Asset instance);
    #endregion
		
		public AssetDataContext() : 
				base(global::SparkCycleListener.DataModel.Properties.Settings.Default.MfrMachineDataLaptopConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AssetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AssetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AssetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AssetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Asset> Assets
		{
			get
			{
				return this.GetTable<Asset>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asset")]
	public partial class Asset : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _AssetNumber;
		
		private bool _SparkDeviceInstalled;
		
		private bool _SparkEnabled;
		
		private System.Nullable<bool> _HandledInCloud;
		
		private System.Nullable<int> _ExpectedCycleTime;
		
		private System.Nullable<decimal> _CycleTimeGracePeriodFactor;
		
		private System.Nullable<int> _HeartBeatsRequired;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAssetNumberChanging(string value);
    partial void OnAssetNumberChanged();
    partial void OnSparkDeviceInstalledChanging(bool value);
    partial void OnSparkDeviceInstalledChanged();
    partial void OnSparkEnabledChanging(bool value);
    partial void OnSparkEnabledChanged();
    partial void OnHandledInCloudChanging(System.Nullable<bool> value);
    partial void OnHandledInCloudChanged();
    partial void OnExpectedCycleTimeChanging(System.Nullable<int> value);
    partial void OnExpectedCycleTimeChanged();
    partial void OnCycleTimeGracePeriodFactorChanging(System.Nullable<decimal> value);
    partial void OnCycleTimeGracePeriodFactorChanged();
    partial void OnHeartBeatsRequiredChanging(System.Nullable<int> value);
    partial void OnHeartBeatsRequiredChanged();
    #endregion
		
		public Asset()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetNumber", DbType="VarChar(50)")]
		public string AssetNumber
		{
			get
			{
				return this._AssetNumber;
			}
			set
			{
				if ((this._AssetNumber != value))
				{
					this.OnAssetNumberChanging(value);
					this.SendPropertyChanging();
					this._AssetNumber = value;
					this.SendPropertyChanged("AssetNumber");
					this.OnAssetNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SparkDeviceInstalled", DbType="Bit NOT NULL")]
		public bool SparkDeviceInstalled
		{
			get
			{
				return this._SparkDeviceInstalled;
			}
			set
			{
				if ((this._SparkDeviceInstalled != value))
				{
					this.OnSparkDeviceInstalledChanging(value);
					this.SendPropertyChanging();
					this._SparkDeviceInstalled = value;
					this.SendPropertyChanged("SparkDeviceInstalled");
					this.OnSparkDeviceInstalledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SparkEnabled", DbType="Bit NOT NULL")]
		public bool SparkEnabled
		{
			get
			{
				return this._SparkEnabled;
			}
			set
			{
				if ((this._SparkEnabled != value))
				{
					this.OnSparkEnabledChanging(value);
					this.SendPropertyChanging();
					this._SparkEnabled = value;
					this.SendPropertyChanged("SparkEnabled");
					this.OnSparkEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HandledInCloud", DbType="Bit")]
		public System.Nullable<bool> HandledInCloud
		{
			get
			{
				return this._HandledInCloud;
			}
			set
			{
				if ((this._HandledInCloud != value))
				{
					this.OnHandledInCloudChanging(value);
					this.SendPropertyChanging();
					this._HandledInCloud = value;
					this.SendPropertyChanged("HandledInCloud");
					this.OnHandledInCloudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedCycleTime", DbType="Int")]
		public System.Nullable<int> ExpectedCycleTime
		{
			get
			{
				return this._ExpectedCycleTime;
			}
			set
			{
				if ((this._ExpectedCycleTime != value))
				{
					this.OnExpectedCycleTimeChanging(value);
					this.SendPropertyChanging();
					this._ExpectedCycleTime = value;
					this.SendPropertyChanged("ExpectedCycleTime");
					this.OnExpectedCycleTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CycleTimeGracePeriodFactor", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> CycleTimeGracePeriodFactor
		{
			get
			{
				return this._CycleTimeGracePeriodFactor;
			}
			set
			{
				if ((this._CycleTimeGracePeriodFactor != value))
				{
					this.OnCycleTimeGracePeriodFactorChanging(value);
					this.SendPropertyChanging();
					this._CycleTimeGracePeriodFactor = value;
					this.SendPropertyChanged("CycleTimeGracePeriodFactor");
					this.OnCycleTimeGracePeriodFactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeartBeatsRequired", DbType="Int")]
		public System.Nullable<int> HeartBeatsRequired
		{
			get
			{
				return this._HeartBeatsRequired;
			}
			set
			{
				if ((this._HeartBeatsRequired != value))
				{
					this.OnHeartBeatsRequiredChanging(value);
					this.SendPropertyChanging();
					this._HeartBeatsRequired = value;
					this.SendPropertyChanged("HeartBeatsRequired");
					this.OnHeartBeatsRequiredChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
