#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkCycleListener.DataModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MfgMachineDataDev")]
	public partial class MachineStateDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMachineState(MachineState instance);
    partial void UpdateMachineState(MachineState instance);
    partial void DeleteMachineState(MachineState instance);
    #endregion
		
		public MachineStateDataContext() : 
				base(global::SparkCycleListener.DataModel.Properties.Settings.Default.MfgMachineDataDevConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MachineStateDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MachineStateDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MachineStateDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MachineStateDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MachineState> MachineStates
		{
			get
			{
				return this.GetTable<MachineState>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MachineState")]
	public partial class MachineState : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _AssetNumber;
		
		private bool _MachineState1;
		
		private System.DateTime _DateTime;
		
		private bool _ProcessedByService;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAssetNumberChanging(string value);
    partial void OnAssetNumberChanged();
    partial void OnMachineState1Changing(bool value);
    partial void OnMachineState1Changed();
    partial void OnDateTimeChanging(System.DateTime value);
    partial void OnDateTimeChanged();
    partial void OnProcessedByServiceChanging(bool value);
    partial void OnProcessedByServiceChanged();
    #endregion
		
		public MachineState()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetNumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string AssetNumber
		{
			get
			{
				return this._AssetNumber;
			}
			set
			{
				if ((this._AssetNumber != value))
				{
					this.OnAssetNumberChanging(value);
					this.SendPropertyChanging();
					this._AssetNumber = value;
					this.SendPropertyChanged("AssetNumber");
					this.OnAssetNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="MachineState", Storage="_MachineState1", DbType="Bit NOT NULL")]
		public bool MachineState1
		{
			get
			{
				return this._MachineState1;
			}
			set
			{
				if ((this._MachineState1 != value))
				{
					this.OnMachineState1Changing(value);
					this.SendPropertyChanging();
					this._MachineState1 = value;
					this.SendPropertyChanged("MachineState1");
					this.OnMachineState1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL")]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessedByService", DbType="Bit NOT NULL")]
		public bool ProcessedByService
		{
			get
			{
				return this._ProcessedByService;
			}
			set
			{
				if ((this._ProcessedByService != value))
				{
					this.OnProcessedByServiceChanging(value);
					this.SendPropertyChanging();
					this._ProcessedByService = value;
					this.SendPropertyChanged("ProcessedByService");
					this.OnProcessedByServiceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
